services:
  database:
    container_name: database
    expose:
      - "5432:5432"
    env_file:
      - .env
    image: postgres:16.2-alpine3.19
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  backend:
#    image: "insert github repo here"
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    expose:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy

#  cf:
#    image: cloudflare/cloudflared
#    restart: always
#    command: tunnel --no-autoupdate run
#    environment:
#      - TUNNEL_TOKEN=TOKEN
volumes:
  database:
